version: '3.8'

services:
  mysql:
    image: forum-mysql
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: forum
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      forum-network:
        ipv4_address: 172.30.0.2

  forum:
    image: forum-app
    container_name: forum-container
    depends_on:
      - mysql
    ports:
      - "443:443"
    environment:
      CERT_PATH: /app/ssl_tls/cert.pem
      KEY_PATH: /app/ssl_tls/key.pem
    command: ["/app/forum-app"]
    networks:
      forum-network:
        ipv4_address: 172.30.0.3

networks:
  forum-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
