version: '3.8'

services:
  mysql:
    image: forum-mysql
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: forum
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - forum-network  # Réseau interne, non exposé à l'extérieur

  forum:
    image: forum-app
    container_name: forum-container
    depends_on:
      - mysql
    networks:
      - forum-network
    ports:
      - "443:443"  # Expose le port 443 de l'hôte vers le conteneur
    environment:
      CERT_PATH: /app/ssl_tls/cert.pem
      KEY_PATH: /app/ssl_tls/key.pem
    command: ["/app/forum-app"]

networks:
  forum-network:
    driver: bridge
