version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: forum-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: forum
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./databases/forum.sql:/docker-entrypoint-initdb.d/forum.sql
    ports:
      - "3306:3306"
